name: portfolio
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  chewie: ^1.5.0
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  lottie: ^2.3.2
  url_launcher: ^6.1.11
  video_player: ^2.7.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/videos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: Caprasimo
      fonts:
        - asset: assets/fonts/Caprasimo/Caprasimo-Regular.ttf
    - family: Narnoor
      fonts:
        - asset: assets/fonts/Narnoor/Narnoor-Regular.ttf
    - family: Belanosima
      fonts:
        - asset: assets/fonts/Belanosima/Belanosima-Regular.ttf